[project]
name = "geogrid"
version = "0.2.0"
description = "PASTOR MALDONADO"
authors = [
    {name = "Eduardo",email = "eduardo.vchaves23@gmail.com"}
]
requires-python = ">=3.13,<4.0"
dependencies = [
    "requests (>=2.32.0,<3.0.0)",
    "pandas (>=3.0.5,<4.0.0)",
    "fastapi[standard] (>=0.141.1,<0.142.0)",
    "slowapi (>=0.1.10,<0.2.0)"
]

[tool.poetry]
package-mode = false

[tool.hatch.build.targets.wheel]
packages = ["core", "v1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
